### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by remrem** [BlogoText/BlogoText.org#1]
Pour reprendre [la liste de chose à faire](https://github.com/BlogoText/blogotext/issues/238#issuecomment-295218385)
- [x] Les liens en en-tête sont collés, c'est dommage.
- [ ] Ajouter dans les liens à droite le dépôt github
- [x] Retirer dans les liens les liens partagés
- [x] font Roboto ne veut pas se charger [cf. comment](#issuecomment-297965959)
- [ ] Il manque une favicon. _voir logo_
- [x] manque un titre (au prochain refresh par le cron)
- [x] listes à puces sont trop condensées
- [ ] Cron updates à revoir
- [ ] Ajout du logo
